export const REGIONS = [
  "Celé Slovensko",
  "Bratislavský kraj",
  "Trnavský kraj",
  "Trenčiansky kraj",
  "Nitriansky kraj",
  "Žilinský kraj",
  "Banskobystrický kraj",
  "Prešovský kraj",
  "Košický kraj",
] as const;

export type Region = (typeof REGIONS)[number];

// Hlavné CPV divízie (dvojciferné kódy)
export const CPV_DIVISIONS: { code: string; name: string }[] = [
  { code: "03", name: "Poľnohospodárske, farmárske, rybárske a lesnícke produkty" },
  { code: "09", name: "Ropné produkty, palivá, elektrina" },
  { code: "14", name: "Ťažobné a súvisiace produkty" },
  { code: "15", name: "Potraviny, nápoje, tabak" },
  { code: "16", name: "Poľnohospodárske stroje" },
  { code: "18", name: "Odevy, obuv, kožené výrobky" },
  { code: "19", name: "Kožené a textilné výrobky" },
  { code: "22", name: "Tlačené výrobky a súvisiace materiály" },
  { code: "24", name: "Chemické produkty" },
  { code: "30", name: "Kancelárska a výpočtová technika" },
  { code: "31", name: "Elektrické stroje a zariadenia" },
  { code: "32", name: "Rádiové, televízne a telekomunikačné zariadenia" },
  { code: "33", name: "Zdravotnícke zariadenia, lieky, pomôcky" },
  { code: "34", name: "Dopravné prostriedky a súvisiace produkty" },
  { code: "35", name: "Bezpečnostné a záchranné zariadenia" },
  { code: "37", name: "Hudobné nástroje, športové potreby, hry" },
  { code: "38", name: "Laboratórne, optické a presné prístroje" },
  { code: "39", name: "Nábytok a domáce spotrebiče" },
  { code: "41", name: "Zachytávaná a čistená voda" },
  { code: "42", name: "Priemyselné stroje" },
  { code: "43", name: "Banské, stavebné a poľnohospodárske stroje" },
  { code: "44", name: "Stavebné konštrukcie a materiály" },
  { code: "45", name: "Stavebné práce" },
  { code: "48", name: "Softvérové balíky a informačné systémy" },
  { code: "50", name: "Opravárske a údržbárske služby" },
  { code: "51", name: "Inštalačné služby" },
  { code: "55", name: "Ubytovacie, reštauračné a maloobchodné služby" },
  { code: "60", name: "Dopravné služby" },
  { code: "63", name: "Podporné a pomocné dopravné služby" },
  { code: "64", name: "Poštové a telekomunikačné služby" },
  { code: "65", name: "Verejné služby (voda, energie)" },
  { code: "66", name: "Finančné a poisťovacie služby" },
  { code: "70", name: "Služby v oblasti nehnuteľností" },
  { code: "71", name: "Architektonické, stavebné a inžinierske služby" },
  { code: "72", name: "IT služby: konzultácie, vývoj softvéru, internet" },
  { code: "73", name: "Výskumné a vývojové služby" },
  { code: "75", name: "Verejná správa, obrana a sociálne zabezpečenie" },
  { code: "76", name: "Služby v ropnom a plynárenskom priemysle" },
  { code: "77", name: "Poľnohospodárske, lesnícke a záhradnícke služby" },
  { code: "79", name: "Podnikateľské služby: právo, marketing, poradenstvo" },
  { code: "80", name: "Vzdelávacie a školiace služby" },
  { code: "85", name: "Zdravotnícke a sociálne služby" },
  { code: "90", name: "Kanalizácia, odpad, čistenie a ekologické služby" },
  { code: "92", name: "Rekreačné, kultúrne a športové služby" },
  { code: "98", name: "Ostatné komunálne, sociálne a osobné služby" },
];
