/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PredplatneRouteImport } from './routes/predplatne'
import { Route as OchranaOsobnychUdajovRouteImport } from './routes/ochrana-osobnych-udajov'
import { Route as ObjednavkaRouteImport } from './routes/objednavka'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZakazkaIdRouteImport } from './routes/zakazka.$id'
import { Route as PravneReklamacnyPoriadokRouteImport } from './routes/pravne.reklamacny-poriadok'
import { Route as PravneOpakovanePlatbyRouteImport } from './routes/pravne.opakovane-platby'
import { Route as PravneObchodnePodmienkyRouteImport } from './routes/pravne.obchodne-podmienky'
import { Route as PravneGdprRouteImport } from './routes/pravne.gdpr'
import { Route as PravneCookiesRouteImport } from './routes/pravne.cookies'
import { Route as PlatbaVysledokRouteImport } from './routes/platba.vysledok'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ZakazkyKategoriaKategoriaRouteImport } from './routes/zakazky.kategoria.$kategoria'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'
import { Route as ZakazkyKategoriaKategoriaKrajRouteImport } from './routes/zakazky.kategoria.$kategoria.$kraj'

const PredplatneRoute = PredplatneRouteImport.update({
  id: '/predplatne',
  path: '/predplatne',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnychUdajovRoute = OchranaOsobnychUdajovRouteImport.update({
  id: '/ochrana-osobnych-udajov',
  path: '/ochrana-osobnych-udajov',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjednavkaRoute = ObjednavkaRouteImport.update({
  id: '/objednavka',
  path: '/objednavka',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakazkaIdRoute = ZakazkaIdRouteImport.update({
  id: '/zakazka/$id',
  path: '/zakazka/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PravneReklamacnyPoriadokRoute =
  PravneReklamacnyPoriadokRouteImport.update({
    id: '/pravne/reklamacny-poriadok',
    path: '/pravne/reklamacny-poriadok',
    getParentRoute: () => rootRouteImport,
  } as any)
const PravneOpakovanePlatbyRoute = PravneOpakovanePlatbyRouteImport.update({
  id: '/pravne/opakovane-platby',
  path: '/pravne/opakovane-platby',
  getParentRoute: () => rootRouteImport,
} as any)
const PravneObchodnePodmienkyRoute = PravneObchodnePodmienkyRouteImport.update({
  id: '/pravne/obchodne-podmienky',
  path: '/pravne/obchodne-podmienky',
  getParentRoute: () => rootRouteImport,
} as any)
const PravneGdprRoute = PravneGdprRouteImport.update({
  id: '/pravne/gdpr',
  path: '/pravne/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const PravneCookiesRoute = PravneCookiesRouteImport.update({
  id: '/pravne/cookies',
  path: '/pravne/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatbaVysledokRoute = PlatbaVysledokRouteImport.update({
  id: '/platba/vysledok',
  path: '/platba/vysledok',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ZakazkyKategoriaKategoriaRoute =
  ZakazkyKategoriaKategoriaRouteImport.update({
    id: '/zakazky/kategoria/$kategoria',
    path: '/zakazky/kategoria/$kategoria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakazkyKategoriaKategoriaKrajRoute =
  ZakazkyKategoriaKategoriaKrajRouteImport.update({
    id: '/$kraj',
    path: '/$kraj',
    getParentRoute: () => ZakazkyKategoriaKategoriaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cennik': typeof CennikRoute
  '/kontakt': typeof KontaktRoute
  '/objednavka': typeof ObjednavkaRoute
  '/ochrana-osobnych-udajov': typeof OchranaOsobnychUdajovRoute
  '/predplatne': typeof PredplatneRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/platba/vysledok': typeof PlatbaVysledokRoute
  '/pravne/cookies': typeof PravneCookiesRoute
  '/pravne/gdpr': typeof PravneGdprRoute
  '/pravne/obchodne-podmienky': typeof PravneObchodnePodmienkyRoute
  '/pravne/opakovane-platby': typeof PravneOpakovanePlatbyRoute
  '/pravne/reklamacny-poriadok': typeof PravneReklamacnyPoriadokRoute
  '/zakazka/$id': typeof ZakazkaIdRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/zakazky/kategoria/$kategoria': typeof ZakazkyKategoriaKategoriaRouteWithChildren
  '/zakazky/kategoria/$kategoria/$kraj': typeof ZakazkyKategoriaKategoriaKrajRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cennik': typeof CennikRoute
  '/kontakt': typeof KontaktRoute
  '/objednavka': typeof ObjednavkaRoute
  '/ochrana-osobnych-udajov': typeof OchranaOsobnychUdajovRoute
  '/predplatne': typeof PredplatneRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/platba/vysledok': typeof PlatbaVysledokRoute
  '/pravne/cookies': typeof PravneCookiesRoute
  '/pravne/gdpr': typeof PravneGdprRoute
  '/pravne/obchodne-podmienky': typeof PravneObchodnePodmienkyRoute
  '/pravne/opakovane-platby': typeof PravneOpakovanePlatbyRoute
  '/pravne/reklamacny-poriadok': typeof PravneReklamacnyPoriadokRoute
  '/zakazka/$id': typeof ZakazkaIdRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/zakazky/kategoria/$kategoria': typeof ZakazkyKategoriaKategoriaRouteWithChildren
  '/zakazky/kategoria/$kategoria/$kraj': typeof ZakazkyKategoriaKategoriaKrajRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cennik': typeof CennikRoute
  '/kontakt': typeof KontaktRoute
  '/objednavka': typeof ObjednavkaRoute
  '/ochrana-osobnych-udajov': typeof OchranaOsobnychUdajovRoute
  '/predplatne': typeof PredplatneRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/platba/vysledok': typeof PlatbaVysledokRoute
  '/pravne/cookies': typeof PravneCookiesRoute
  '/pravne/gdpr': typeof PravneGdprRoute
  '/pravne/obchodne-podmienky': typeof PravneObchodnePodmienkyRoute
  '/pravne/opakovane-platby': typeof PravneOpakovanePlatbyRoute
  '/pravne/reklamacny-poriadok': typeof PravneReklamacnyPoriadokRoute
  '/zakazka/$id': typeof ZakazkaIdRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/zakazky/kategoria/$kategoria': typeof ZakazkyKategoriaKategoriaRouteWithChildren
  '/zakazky/kategoria/$kategoria/$kraj': typeof ZakazkyKategoriaKategoriaKrajRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cennik'
    | '/kontakt'
    | '/objednavka'
    | '/ochrana-osobnych-udajov'
    | '/predplatne'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/platba/vysledok'
    | '/pravne/cookies'
    | '/pravne/gdpr'
    | '/pravne/obchodne-podmienky'
    | '/pravne/opakovane-platby'
    | '/pravne/reklamacny-poriadok'
    | '/zakazka/$id'
    | '/api/public/stats'
    | '/zakazky/kategoria/$kategoria'
    | '/zakazky/kategoria/$kategoria/$kraj'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cennik'
    | '/kontakt'
    | '/objednavka'
    | '/ochrana-osobnych-udajov'
    | '/predplatne'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/platba/vysledok'
    | '/pravne/cookies'
    | '/pravne/gdpr'
    | '/pravne/obchodne-podmienky'
    | '/pravne/opakovane-platby'
    | '/pravne/reklamacny-poriadok'
    | '/zakazka/$id'
    | '/api/public/stats'
    | '/zakazky/kategoria/$kategoria'
    | '/zakazky/kategoria/$kategoria/$kraj'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cennik'
    | '/kontakt'
    | '/objednavka'
    | '/ochrana-osobnych-udajov'
    | '/predplatne'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/platba/vysledok'
    | '/pravne/cookies'
    | '/pravne/gdpr'
    | '/pravne/obchodne-podmienky'
    | '/pravne/opakovane-platby'
    | '/pravne/reklamacny-poriadok'
    | '/zakazka/$id'
    | '/api/public/stats'
    | '/zakazky/kategoria/$kategoria'
    | '/zakazky/kategoria/$kategoria/$kraj'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CennikRoute: typeof CennikRoute
  KontaktRoute: typeof KontaktRoute
  ObjednavkaRoute: typeof ObjednavkaRoute
  OchranaOsobnychUdajovRoute: typeof OchranaOsobnychUdajovRoute
  PredplatneRoute: typeof PredplatneRoute
  PlatbaVysledokRoute: typeof PlatbaVysledokRoute
  PravneCookiesRoute: typeof PravneCookiesRoute
  PravneGdprRoute: typeof PravneGdprRoute
  PravneObchodnePodmienkyRoute: typeof PravneObchodnePodmienkyRoute
  PravneOpakovanePlatbyRoute: typeof PravneOpakovanePlatbyRoute
  PravneReklamacnyPoriadokRoute: typeof PravneReklamacnyPoriadokRoute
  ZakazkaIdRoute: typeof ZakazkaIdRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
  ZakazkyKategoriaKategoriaRoute: typeof ZakazkyKategoriaKategoriaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predplatne': {
      id: '/predplatne'
      path: '/predplatne'
      fullPath: '/predplatne'
      preLoaderRoute: typeof PredplatneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnych-udajov': {
      id: '/ochrana-osobnych-udajov'
      path: '/ochrana-osobnych-udajov'
      fullPath: '/ochrana-osobnych-udajov'
      preLoaderRoute: typeof OchranaOsobnychUdajovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objednavka': {
      id: '/objednavka'
      path: '/objednavka'
      fullPath: '/objednavka'
      preLoaderRoute: typeof ObjednavkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakazka/$id': {
      id: '/zakazka/$id'
      path: '/zakazka/$id'
      fullPath: '/zakazka/$id'
      preLoaderRoute: typeof ZakazkaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravne/reklamacny-poriadok': {
      id: '/pravne/reklamacny-poriadok'
      path: '/pravne/reklamacny-poriadok'
      fullPath: '/pravne/reklamacny-poriadok'
      preLoaderRoute: typeof PravneReklamacnyPoriadokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravne/opakovane-platby': {
      id: '/pravne/opakovane-platby'
      path: '/pravne/opakovane-platby'
      fullPath: '/pravne/opakovane-platby'
      preLoaderRoute: typeof PravneOpakovanePlatbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravne/obchodne-podmienky': {
      id: '/pravne/obchodne-podmienky'
      path: '/pravne/obchodne-podmienky'
      fullPath: '/pravne/obchodne-podmienky'
      preLoaderRoute: typeof PravneObchodnePodmienkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravne/gdpr': {
      id: '/pravne/gdpr'
      path: '/pravne/gdpr'
      fullPath: '/pravne/gdpr'
      preLoaderRoute: typeof PravneGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravne/cookies': {
      id: '/pravne/cookies'
      path: '/pravne/cookies'
      fullPath: '/pravne/cookies'
      preLoaderRoute: typeof PravneCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platba/vysledok': {
      id: '/platba/vysledok'
      path: '/platba/vysledok'
      fullPath: '/platba/vysledok'
      preLoaderRoute: typeof PlatbaVysledokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/zakazky/kategoria/$kategoria': {
      id: '/zakazky/kategoria/$kategoria'
      path: '/zakazky/kategoria/$kategoria'
      fullPath: '/zakazky/kategoria/$kategoria'
      preLoaderRoute: typeof ZakazkyKategoriaKategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakazky/kategoria/$kategoria/$kraj': {
      id: '/zakazky/kategoria/$kategoria/$kraj'
      path: '/$kraj'
      fullPath: '/zakazky/kategoria/$kategoria/$kraj'
      preLoaderRoute: typeof ZakazkyKategoriaKategoriaKrajRouteImport
      parentRoute: typeof ZakazkyKategoriaKategoriaRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ZakazkyKategoriaKategoriaRouteChildren {
  ZakazkyKategoriaKategoriaKrajRoute: typeof ZakazkyKategoriaKategoriaKrajRoute
}

const ZakazkyKategoriaKategoriaRouteChildren: ZakazkyKategoriaKategoriaRouteChildren =
  {
    ZakazkyKategoriaKategoriaKrajRoute: ZakazkyKategoriaKategoriaKrajRoute,
  }

const ZakazkyKategoriaKategoriaRouteWithChildren =
  ZakazkyKategoriaKategoriaRoute._addFileChildren(
    ZakazkyKategoriaKategoriaRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CennikRoute: CennikRoute,
  KontaktRoute: KontaktRoute,
  ObjednavkaRoute: ObjednavkaRoute,
  OchranaOsobnychUdajovRoute: OchranaOsobnychUdajovRoute,
  PredplatneRoute: PredplatneRoute,
  PlatbaVysledokRoute: PlatbaVysledokRoute,
  PravneCookiesRoute: PravneCookiesRoute,
  PravneGdprRoute: PravneGdprRoute,
  PravneObchodnePodmienkyRoute: PravneObchodnePodmienkyRoute,
  PravneOpakovanePlatbyRoute: PravneOpakovanePlatbyRoute,
  PravneReklamacnyPoriadokRoute: PravneReklamacnyPoriadokRoute,
  ZakazkaIdRoute: ZakazkaIdRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
  ZakazkyKategoriaKategoriaRoute: ZakazkyKategoriaKategoriaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
