// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmssxnluhjhzqmutflbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtc3N4bmx1aGpoenFtdXRmbGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMyNzQ2MzcsImV4cCI6MjA5ODg1MDYzN30.-pl_XY06sOShITzwFJkYZcmHcfDaJFI_x9J3nxXVbiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});